name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Vale
      uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084
      with:
        files: '["docs", "samples"]'
        fail_on_error: true
        filter_mode: nofilter
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 